### ISSUE TITLE
Nutzerspezifische Dialoge entwickeln

### ISSUE THREAD

**Issue by sophiekern** [ID-Start-Winter22/Remy-Bot#22]

**Comment by AmyWin48** [comment]
sind fertig und liegen auf dem figma https://www.figma.com/file/SE4QnnMFyrn2BfjIZEqrWy/Storyboard?node-id=143%3A277&t=Bgxc6ys373JnbaPe-0
@sophiekern schaust Du mal rüber?

**Comment by sophiekern** [comment]
Habe ich durchgeschaut und auch gleich ins Wiki übernommen. Danke dir!
