### ISSUE TITLE
Wiki Seite zu Sprint 1

### ISSUE THREAD

**Issue by sophiekern** [ID-Start-Winter22/Remy-Bot#23]

**Comment by AmyWin48** [comment]
kann ich dir da noch ne task abnehmen @sophiekern ?

**Comment by sophiekern** [comment]
Danke, ich bin soweit fertig. Könntest du bitte mal drüberlesen ob alles so passt? Link füge ich dann am Ende noch ein, sobald die PDF fertig ist.

**Comment by AmyWin48** [comment]
ja nice, passt gut! Danke Dir
