### ISSUE TITLE
basic rasa bot entfernen

### ISSUE THREAD

**Issue by davifhel** [ID-Start-Winter22/Remy-Bot#35]

**Comment by RimLightMedia** [comment]
Lieber @davifhel bitte schau dir doch mal diese issue bis Freitag an.

**Comment by davifhel** [comment]
beim nächsten push ist alles weg.

**Comment by AmyWin48** [comment]
mit dem closen warte ich bis @RimLightMedia gepusht hat

**Comment by davifhel** [comment]
ja würde ich sagen, aber dann frag @RimLightMedia nochmal ob er die reste in seiner version auch schon entfernt hat?

**Comment by davifhel** [comment]
ist beendet!
