### ISSUE TITLE
PDF mit Design Ergebnissen

### ISSUE THREAD

**Issue by AmyWin48** [ID-Start-Winter22/Remy-Bot#36]

**Comment by AmyWin48** [comment]
ist in Bearbeitung von @davifhel

**Comment by davifhel** [comment]
VORSCHLAG: Layout & Gestaltung des Design-Résumés 

![Uploading 6EBA3E87-C1D0-4D9A-A796-5F17BD09844F.jpeg…]()

**Comment by AmyWin48** [comment]
hab die Charakterseite fertig und dir per mail geschickt @davifhel

**Comment by davifhel** [comment]
@AmyWin48 @sophiekern @RimLightMedia 
Design Résumé ist meinerseits fertig und liegt im repository. schaut bitte mal drüber und gebt feedback. 

@sophiekern du kannst die Datei gleich aus dem repository ins wiki verlinken.

**Comment by AmyWin48** [comment]
@davifhel geht klar, sieht gut aus, danke dir

**Comment by sophiekern** [comment]
@davifhel Super danke – Datei ist im Wiki verlinkt (ganz oben unter Sprint 1).
