### ISSUE TITLE
Kurzgeschichte über Remy

### ISSUE THREAD

**Issue by AmyWin48** [ID-Start-Winter22/Remy-Bot#37]

**Comment by AmyWin48** [comment]
gerne drüber lesen, Anmerkungen willkommen @davifhel 

Remy Story 
 
Remy ist eine junge und liebenswürdige Ratte. Er ist überaus freundlich, stets gut gelaunt und hat meist einen lockeren Spruch auf den Lippen. Remy liebt es zu kochen! Seit kurzem ist er sogar Koch in Ausbildung und wird von dem besten 5-Sterne-Koch, weit und breit unterrichtet. Chef Délicieux meinte, Remy hätte ihn mit seiner Passion für schnell, fabelhafte Gerichte mit einfachen Zutaten einfach umgehauen. 
 
Remy lebt in Frankreich, um genauer zu sein, in Paris. Was viele nicht wissen, Paris genießt nicht nur den Ruf, die Stadt der Liebe zu sein, sondern sie ist auch für ihre fabelhaften Restaurants, Confiserien und Cafés bekannt. Leider ist Paris ebenso schön, wie teuer und Remys Familie hat nicht besonders viel Geld. So hat er sich schon früh darin versucht, auch mit einem kleinen Budget großartige Gerichte zu zaubern. 
 
Remy ist von seiner Berufung so begeistert, dass er auch Dich gerne motivieren würde, öfters den Kochlöffel zu schwingen. Dazu hat er sich unzählige, einfache Gerichte für den schmalen Geldbeutel ausgedacht, die Ihr zusammen kochen könnt. 
 
Schreib Remy doch einfach mal ein paar Zutaten, die Du zu Hause hast und such Dir ein passendes Rezept aus seinen Vorschlägen aus. Und wer weiß, zusammen mit Remy wird Dir das Kochen vielleicht bald schon ähnlich viel Freude bereiten, wie ihm.

**Comment by davifhel** [comment]
haha 10/10. würde vllt noch den Namen des Kochs ändern auf den ausm film aber da können wir nochmal drüber reden. 2. Absatz mein favorite.

**Comment by AmyWin48** [comment]
ok danke dir, wird gemacht
