### ISSUE TITLE
Storyboard für Remy

### ISSUE THREAD

**Issue by RimLightMedia** [ID-Start-Winter22/Remy-Bot#39]

**Comment by RimLightMedia** [comment]
@AmyWin48 Bitte schau doch einmal über mein storyboard drüber hier der Link:

https://miro.com/welcomeonboard/MnQ3ZE13SGxwbEdiMzFyYmhYbkFwelA0MmNWekNyRkdjZVd5QTBRUGNyQzYxSm5sNUNhSmJIMk9aMVpxNGRxd3wzNDU4NzY0NTM2MDg5MjI4NjE1fDI=?share_link_id=363459840545

**Comment by AmyWin48** [comment]
sieht super aus, danke Dir
