### ISSUE TITLE
Charakter Résumé

### ISSUE THREAD

**Issue by davifhel** [ID-Start-Winter22/Remy-Bot#41]
@AmyWin48 hast du die Datei schon fertig??

**Comment by AmyWin48** [comment]
ja, hab ich dir gemailt, passt dir das so?

**Comment by AmyWin48** [comment]
@davifhel

**Comment by davifhel** [comment]
top danke dir passt denke ich, falls etwas nicht stimmt merken es die anderen wenn sie das gesamte resume durchgehen
