### ISSUE TITLE
Forms implementieren

### ISSUE THREAD

**Issue by davifhel** [ID-Start-Winter22/Remy-Bot#43]

**Comment by RimLightMedia** [comment]
@davifhel ich habe uns für morgen eine Termin beim Michael ausgemacht. Er wird uns bei den Finalen schritten für die Forms helfen.

**Comment by RimLightMedia** [comment]
@davifhel ich habe uns für morgen eine Termin beim Michael ausgemacht. Er wird uns bei den Finalen schritten für die Forms helfen.
