### ISSUE TITLE
Chefkoch API o.ä. als Datengrundlage organisieren

### ISSUE THREAD

**Issue by davifhel** [ID-Start-Winter22/Remy-Bot#44]

**Comment by AmyWin48** [comment]
@RimLightMedia magst Du vllt die Soupseite verlinken?

**Comment by RimLightMedia** [comment]
Hi Leute ich habe wie besprochen, da es keine Öffentlich zugänglich bzw. gut gewartet API für Kochrezepte gibt, den HTML.parser für die Chefkoch Seite erstellt. Aktuelle Funktionieren alle angepeilten Funktionen aber die Anbindung an das RASA Framework stellt sich alls schwieriger als gedacht raus.
