### ISSUE TITLE
Tone-of-voice iterieren: Rémy sollte an manchen stellen noch freudiger, motivierter und enthusiastisch klingen, sodass User:innen mehr das Gefühl von einer Unterstützung haben 

### ISSUE THREAD

**Issue by AmyWin48** [ID-Start-Winter22/Remy-Bot#45]
@davifhel kannst Du da nochmal drüber gehen?

**Comment by davifhel** [comment]
klaro mach ich, die updates werde ich auf das Figma-Board mit den Stories legen.

**Comment by davifhel** [comment]
die Updates habe ich auf das Figma-Board geladen @AmyWin48 bitte mal korrektur-lesen
