### ISSUE TITLE
Digitales Zuhause Rémy 

### ISSUE THREAD

**Issue by AmyWin48** [ID-Start-Winter22/Remy-Bot#46]
Ideensammlung: Mülltonne, Kanalisation, in einer Küche 
soll Rémy einen Körper bekommen? - vielleicht muss Rémy selbst im Zuhause gar nicht sichtbar sein 
- arbeiten mit Dalli2? 
@davifhel

**Comment by davifhel** [comment]
@sophiekern übernimmt das!

**Comment by sophiekern** [comment]
Hier der Figma Link: https://www.figma.com/file/Xcnw0wxL7jWekJyL30kLGW/Projektmodul-Digitales-Zuhause?node-id=0%3A1&t=0Ct7txiRD3IbfC7l-0
Bitte anschauen und gerne Feedback geben! @davifhel

**Comment by davifhel** [comment]
cooolio
