### ISSUE TITLE
PDF mit Design Ergebnissen 

### ISSUE THREAD

**Issue by AmyWin48** [ID-Start-Winter22/Remy-Bot#47]
@davifhel da hast Du ja schon die letzte gestaltet könntest Du die Vorlage auch hierfür ran ziehen?

**Comment by sophiekern** [comment]
Hab ich zusammengestellt. Hier der Link zum PDF: 
[SP2_Design_Manual.pdf](https://github.com/ID-Start-Winter22/Remy-Bot/files/10435613/SP2_Design_Manual.pdf)
Kannst du bitte drüber schauen und Bescheid geben, falls du noch was ändern würdest?

**Comment by AmyWin48** [comment]
würde noch den figma link zum digitalen zuhause hinterlegen
