### ISSUE TITLE
Skript für Usability Testing erstellen 

### ISSUE THREAD

**Issue by AmyWin48** [ID-Start-Winter22/Remy-Bot#48]
bis FR können sich vllt mal alle Gedanken machen, worauf wir beim Testing ein Augenmerk legen wollen (z.B. hatt uns Teo in einem kleinen der Fehlermeldung ja schon weiterhelfen können) Vorlage findet man hier auf dem Miro Board
@sophiekern @davifhel @RimLightMedia

**Comment by AmyWin48** [comment]
Vorlage ist ausgefüllt @sophiekern bitte drüber schauen

**Comment by sophiekern** [comment]
Hab ich mir angeschaut, passt von meiner Seite aus. Danke @AmyWin48
